'use strict';
const fs    = require('fs');
const path  = require('path');
const { spawnSync } = require('child_process');

const ROOT        = path.resolve(__dirname, '../..');
const DATA_DIR    = path.join(ROOT, 'pipeline', 'data');
const OUT_FILE    = path.join(ROOT, 'data.ts');
const LEGACY_OUT_FILE = path.join(ROOT, 'data.js');
const GENERATED_TS_FILE = path.join(ROOT, 'src', 'data', 'generated.ts');
const CANARY_SCRIPT = path.join(ROOT, 'pipeline', 'scripts', 'canary-test.ts');
const TSX_BIN     = path.join(ROOT, 'node_modules', '.bin', 'tsx' + (process.platform === 'win32' ? '.cmd' : ''));

const PIPELINE_FIELDS = ['_provenance', '_meta', '_novelty', 'brand', '_staging'];

function stripPipelineFields(obj) {
  const result = { ...obj };
  for (const field of PIPELINE_FIELDS) delete result[field];
  return result;
}

function buildCompatTsOutput() {
  return [
    '// This file is generated by pipeline/scripts/export-to-app.ts',
    '// Do not edit by hand. Update pipeline/data/*.json and rerun the export pipeline.',
    "export { RACQUETS, STRINGS, FRAME_META, FRAME_NOVELTY_PROFILE } from './src/data/generated.js';",
    "export type { FrameMeta, FrameNoveltyProfile, Racquet, StringData } from './src/engine/types.js';",
    ''
  ].join('\n');
}

function buildTsOutput(racquets, strings, frameMeta, frameNoveltyProfile) {
  return [
    '// This file is generated by pipeline/scripts/export-to-app.ts',
    '// Do not edit by hand. Update pipeline/data/*.json and rerun the export pipeline.',
    "import type { FrameMeta, FrameNoveltyProfile, Racquet, StringData } from '../engine/types.js';",
    '',
    `export const RACQUETS: Racquet[] = ${JSON.stringify(racquets, null, 2)};`,
    '',
    `export const STRINGS: StringData[] = ${JSON.stringify(strings, null, 2)};`,
    '',
    `export const FRAME_META: Record<string, FrameMeta> = ${JSON.stringify(frameMeta, null, 2)};`,
    '',
    `export const FRAME_NOVELTY_PROFILE: Record<string, FrameNoveltyProfile> = ${JSON.stringify(frameNoveltyProfile, null, 2)};`,
    ''
  ].join('\n');
}

function clamp(val, min, max) {
  return Math.max(min, Math.min(max, val));
}

function round3(val) {
  return Math.round(val * 1000) / 1000;
}

function norm(val, min, max) {
  if (max === min) return 0.5;
  return clamp((val - min) / (max - min), 0, 1);
}

function percentileRank(sorted, value) {
  if (!sorted.length) return 0;
  if (sorted.length === 1) return 0.5;
  let idx = 0;
  while (idx < sorted.length && sorted[idx] <= value) idx++;
  return round3((idx - 1) / (sorted.length - 1));
}

function getPatternDensity(pattern) {
  const [mains, crosses] = String(pattern || '16x19').split('x').map(Number);
  return (mains || 16) * (crosses || 19);
}

function getAvgBeam(beamWidth) {
  if (!Array.isArray(beamWidth) || beamWidth.length === 0) return 0;
  return beamWidth.reduce((sum, width) => sum + width, 0) / beamWidth.length;
}

function bandHeadSize(headSize) {
  if (headSize <= 98) return 'players';
  if (headSize <= 100) return 'midplus';
  return 'oversize';
}

function bandWeight(weight) {
  if (weight < 305) return 'light';
  if (weight < 320) return 'standard';
  return 'tour';
}

function bandSwingweight(swingweight) {
  if (swingweight < 315) return 'quick';
  if (swingweight < 325) return 'balanced';
  return 'plow';
}

function bandStiffness(stiffness) {
  if (stiffness < 62) return 'flexible';
  if (stiffness < 67) return 'modern';
  return 'firm';
}

function bandBeam(avgBeam) {
  if (avgBeam < 22) return 'thin';
  if (avgBeam < 24) return 'mid';
  return 'thick';
}

function bandDensity(patternDensity) {
  if (patternDensity <= 304) return 'open';
  if (patternDensity <= 323) return 'moderate';
  return 'dense';
}

function buildFrameNoveltyProfiles(frames, frameMeta) {
  const summaries = frames.map((frame) => {
    const patternDensity = getPatternDensity(frame.pattern);
    const avgBeam = getAvgBeam(frame.beamWidth);
    const beamRange = Array.isArray(frame.beamWidth) && frame.beamWidth.length
      ? Math.max(...frame.beamWidth) - Math.min(...frame.beamWidth)
      : 0;
    const openness = 1 - norm(patternDensity, 288, 360);
    const meta = frameMeta[frame.id] || { aeroBonus: 0, comfortTech: 0, spinTech: 0, genBonus: 0 };
    const bands = {
      headSize: bandHeadSize(frame.headSize),
      weight: bandWeight(frame.strungWeight),
      swingweight: bandSwingweight(frame.swingweight),
      stiffness: bandStiffness(frame.stiffness),
      beam: bandBeam(avgBeam),
      density: bandDensity(patternDensity),
      pattern: frame.pattern
    };
    return {
      id: frame.id,
      avgBeam,
      beamRange,
      openness,
      patternDensity,
      bands,
      bucketKey: `${bands.headSize}|${bands.pattern}|${bands.weight}`,
      meta,
      hintWeights: frame._novelty || {
        controlBomber: 0,
        plushLauncher: 0,
        stableWhipper: 0,
        preciseSpinner: 0,
        comfortableAttacker: 0
      },
      frame
    };
  });

  const bucketCounts = {};
  for (const summary of summaries) {
    bucketCounts[summary.bucketKey] = (bucketCounts[summary.bucketKey] || 0) + 1;
  }

  const sortedHeadSizes = summaries.map((s) => s.frame.headSize).sort((a, b) => a - b);
  const sortedWeights = summaries.map((s) => s.frame.strungWeight).sort((a, b) => a - b);
  const sortedSwingweights = summaries.map((s) => s.frame.swingweight).sort((a, b) => a - b);
  const sortedStiffness = summaries.map((s) => s.frame.stiffness).sort((a, b) => a - b);
  const sortedBeams = summaries.map((s) => s.avgBeam).sort((a, b) => a - b);
  const sortedOpenness = summaries.map((s) => s.openness).sort((a, b) => a - b);

  const profile = {};
  for (const summary of summaries) {
    const bucketSize = bucketCounts[summary.bucketKey];
    const percentiles = {
      headSize: percentileRank(sortedHeadSizes, summary.frame.headSize),
      strungWeight: percentileRank(sortedWeights, summary.frame.strungWeight),
      swingweight: percentileRank(sortedSwingweights, summary.frame.swingweight),
      stiffness: percentileRank(sortedStiffness, summary.frame.stiffness),
      avgBeam: percentileRank(sortedBeams, summary.avgBeam),
      openness: percentileRank(sortedOpenness, summary.openness)
    };

    const rarityTags = [];
    if (bucketSize <= 3) rarityTags.push({ id: 'rareBucket', label: 'rare spec bucket', score: 0.35 });
    else if (bucketSize <= 6) rarityTags.push({ id: 'thinBucket', label: 'thin spec bucket', score: 0.2 });

    if (summary.patternDensity >= 352) rarityTags.push({ id: 'densePattern', label: 'very dense pattern', score: 0.16 });
    if (summary.patternDensity <= 304) rarityTags.push({ id: 'openPattern', label: 'very open pattern', score: 0.16 });
    if (percentiles.avgBeam <= 0.15 && percentiles.swingweight >= 0.75) rarityTags.push({ id: 'thinBeamPlow', label: 'thin beam with plow-through', score: 0.14 });
    if (percentiles.stiffness <= 0.2 && summary.meta.comfortTech >= 1.5) rarityTags.push({ id: 'plushTech', label: 'soft flex plus comfort tech', score: 0.12 });
    if (summary.meta.aeroBonus + summary.meta.spinTech >= 3) rarityTags.push({ id: 'spinTechHeavy', label: 'spin-focused tech package', score: 0.12 });
    if (summary.meta.comfortTech >= 2) rarityTags.push({ id: 'comfortTechHeavy', label: 'comfort-heavy tech package', score: 0.12 });
    if (summary.beamRange >= 2) rarityTags.push({ id: 'variableBeam', label: 'variable beam profile', score: 0.08 });

    const rarityScore = round3(clamp(rarityTags.reduce((sum, tag) => sum + tag.score, 0), 0, 1));
    profile[summary.id] = {
      bucketKey: summary.bucketKey,
      bucketSize,
      rarityScore,
      bands: summary.bands,
      percentiles,
      rarityTags,
      hintWeights: summary.hintWeights
    };
  }

  return profile;
}

function main() {
  const isDryRun = process.argv.includes('--dry-run');
  const isVerify = process.argv.includes('--verify');

  const frames  = JSON.parse(fs.readFileSync(path.join(DATA_DIR, 'frames.json'),  'utf8'));
  const strings = JSON.parse(fs.readFileSync(path.join(DATA_DIR, 'strings.json'), 'utf8'));

  const RACQUETS = frames.map(stripPipelineFields);
  const STRINGS  = strings.map(stripPipelineFields);

  const FRAME_META = {};
  for (const frame of frames) {
    if (frame._meta) FRAME_META[frame.id] = frame._meta;
  }

  const FRAME_NOVELTY_PROFILE = buildFrameNoveltyProfiles(frames, FRAME_META);

  const output = buildCompatTsOutput();
  const generatedTsOutput = buildTsOutput(RACQUETS, STRINGS, FRAME_META, FRAME_NOVELTY_PROFILE);

  if (isDryRun) {
    process.stdout.write(output);
    console.error(`\n[dry-run] ${RACQUETS.length} frames, ${STRINGS.length} strings, ${Object.keys(FRAME_META).length} frame meta entries`);
    return;
  }

  fs.writeFileSync(OUT_FILE, output);
  fs.writeFileSync(GENERATED_TS_FILE, generatedTsOutput);
  if (fs.existsSync(LEGACY_OUT_FILE)) {
    fs.unlinkSync(LEGACY_OUT_FILE);
  }
  console.log(`✓ src/data/generated.ts + data.ts written — ${RACQUETS.length} frames, ${STRINGS.length} strings, ${Object.keys(FRAME_META).length} frame meta entries, ${Object.keys(FRAME_NOVELTY_PROFILE).length} novelty profiles`);

  if (isVerify) {
    console.log('\nRunning canary verification...');
    const result = spawnSync(TSX_BIN, [CANARY_SCRIPT], { stdio: 'inherit', shell: true });
    if (result.status !== 0) {
      console.error('\n✗ Canary verification failed');
      process.exit(1);
    }
  }
}

main();
