'use strict';
const fs    = require('fs');
const path  = require('path');
const { spawnSync } = require('child_process');

const ROOT        = path.resolve(__dirname, '../..');
const DATA_DIR    = path.join(ROOT, 'pipeline', 'data');
const OUT_FILE    = path.join(ROOT, 'data.js');
const GENERATED_TS_FILE = path.join(ROOT, 'src', 'data', 'generated.ts');
const CANARY_SCRIPT = path.join(ROOT, 'pipeline', 'scripts', 'canary-test.ts');
const TSX_BIN     = path.join(ROOT, 'node_modules', '.bin', 'tsx' + (process.platform === 'win32' ? '.cmd' : ''));

const PIPELINE_FIELDS = ['_provenance', '_meta', 'brand', '_staging'];

function stripPipelineFields(obj) {
  const result = { ...obj };
  for (const field of PIPELINE_FIELDS) delete result[field];
  return result;
}

function buildJsOutput(racquets, strings, frameMeta) {
  return [
    `const RACQUETS = ${JSON.stringify(racquets, null, 2)};`,
    '',
    `const STRINGS = ${JSON.stringify(strings, null, 2)};`,
    '',
    `const FRAME_META = ${JSON.stringify(frameMeta, null, 2)};`,
    '',
    '// ES Module exports',
    'export { RACQUETS, STRINGS, FRAME_META };',
    ''
  ].join('\n');
}

function buildTsOutput(racquets, strings, frameMeta) {
  return [
    '// This file is generated by pipeline/scripts/export-to-app.ts',
    '// Do not edit by hand. Update pipeline/data/*.json and rerun the export pipeline.',
    "import type { FrameMeta, Racquet, StringData } from '../engine/types.js';",
    '',
    `export const RACQUETS: Racquet[] = ${JSON.stringify(racquets, null, 2)};`,
    '',
    `export const STRINGS: StringData[] = ${JSON.stringify(strings, null, 2)};`,
    '',
    `export const FRAME_META: Record<string, FrameMeta> = ${JSON.stringify(frameMeta, null, 2)};`,
    ''
  ].join('\n');
}

function main() {
  const isDryRun = process.argv.includes('--dry-run');
  const isVerify = process.argv.includes('--verify');

  const frames  = JSON.parse(fs.readFileSync(path.join(DATA_DIR, 'frames.json'),  'utf8'));
  const strings = JSON.parse(fs.readFileSync(path.join(DATA_DIR, 'strings.json'), 'utf8'));

  const RACQUETS = frames.map(stripPipelineFields);
  const STRINGS  = strings.map(stripPipelineFields);

  const FRAME_META = {};
  for (const frame of frames) {
    if (frame._meta) FRAME_META[frame.id] = frame._meta;
  }

  const output = buildJsOutput(RACQUETS, STRINGS, FRAME_META);
  const generatedTsOutput = buildTsOutput(RACQUETS, STRINGS, FRAME_META);

  if (isDryRun) {
    process.stdout.write(output);
    console.error(`\n[dry-run] ${RACQUETS.length} frames, ${STRINGS.length} strings, ${Object.keys(FRAME_META).length} frame meta entries`);
    return;
  }

  fs.writeFileSync(OUT_FILE, output);
  fs.writeFileSync(GENERATED_TS_FILE, generatedTsOutput);
  console.log(`✓ data.js written — ${RACQUETS.length} frames, ${STRINGS.length} strings, ${Object.keys(FRAME_META).length} frame meta entries`);

  if (isVerify) {
    console.log('\nRunning canary verification...');
    const result = spawnSync(TSX_BIN, [CANARY_SCRIPT], { stdio: 'inherit', shell: true });
    if (result.status !== 0) {
      console.error('\n✗ Canary verification failed');
      process.exit(1);
    }
  }
}

main();
